### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by ajiragroup** [rbnkoirala/nepalidate#3]
![image](https://github.com/rbnkoirala/nepalidate/assets/108009061/8d4a7f59-6590-4799-8a61-5ad22469ecef)

```
### Route
```
Form/Nepali Date Demo/Nepali Date Demo
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1683, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/load.py", line 34, in getdoc
    doc = frappe.get_doc(doctype, name)
  File "apps/frappe/frappe/__init__.py", line 1266, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
  File "apps/frappe/frappe/model/base_document.py", line 69, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "apps/frappe/frappe/model/base_document.py", line 99, in import_controller
    raise ImportError(
ImportError: Nepali Date Demo

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"doctype": "Nepali Date Demo",
		"name": "Nepali Date Demo"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.load.getdoc",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "ImportError: Nepali Date Demo",
	"exc_type": "ImportError"
}
```

**Comment by rbnkoirala** [comment]
Now Fixed...
`cd frappe-bench/apps/nepalidate`
`git pull`
`bench --site sitename migrate`

**Comment by ajiragroup** [comment]
great !
